### PR TITLE
Fix impicit MRI configuration calls

### LINKED ISSUE #5044: MRI slow integrator path uses ARKStep-specific API calls on MRIStep memory
- **Type**: Correctness / API misuse
- **Severity**: High
- **Component**: SUNDIALS MRI slow-step configuration
- **Location**:
  - `Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H:414`
  - `Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H:417`
  - `Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H:427`
  - `Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H:441`
  - `Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H:446`

## Problem
After creating the slow integrator with `MRIStepCreate`, the code configures it via `ARKStepSet*` calls (nonlinear/linear solver, stop time, max steps).

## Impact
- API calls may fail or not apply to MRIStep as intended.
- Slow MRI solver configuration may be incorrect in implicit IM/IMEX MRI modes.

## Suggested patch
Use MRIStep-appropriate setters (or generic ARKode setters for all stepper types when available in the targeted SUNDIALS version).

```diff
--- a/Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H
+++ b/Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H
@@
-                flag = ARKStepSetNonlinearSolver(arkode_mem, NLS);
+                flag = MRIStepSetNonlinearSolver(arkode_mem, NLS);
@@
-            flag = ARKStepSetMaxNonlinIters(arkode_mem, max_nonlinear_iters);
+            flag = MRIStepSetMaxNonlinIters(arkode_mem, max_nonlinear_iters);
@@
-                flag = ARKStepSetLinearSolver(arkode_mem, LS, nullptr);
+                flag = MRIStepSetLinearSolver(arkode_mem, LS, nullptr);
@@
-          flag = ARKStepSetStopTime(arkode_mem, stop_time);
+          flag = MRIStepSetStopTime(arkode_mem, stop_time);
@@
-        flag = ARKStepSetMaxNumSteps(arkode_mem, max_num_steps);
+        flag = MRIStepSetMaxNumSteps(arkode_mem, max_num_steps);
```

Prepared by Codex

### PR DESCRIPTION
**Pull request by gardner48**
## Summary

Corrects `Set` function calls to configure the slow integrator with an implicit MRI method. This addresses the issues noted in #5044. The calls changed from `ARKStep` to `MRIStep` would work with SUNDIALS 7.1.0 or newer (when stepper specific `Set` functions were deprecated and replaced with common `ARKode` functions) but would fail with earlier versions of SUNDIALS.

Correct `Set` functions calls to configure an implicit fast integrator in an MRI method to use a fixed-point solver, modify the max number of iterations, or set the linear solver when using a Newton solver.

## Checklist

The proposed changes:
- [x] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

File: Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H [hunk 1]
```diff
@@ -438,12 +438,12 @@ private:
...
         if (set_stop_time) {
             if (amrex::Verbose()) { amrex::Print() << "Stop time: " << stop_time << "\n"; }
-          flag = ARKStepSetStopTime(arkode_mem, stop_time);
+          flag = MRIStepSetStopTime(arkode_mem, stop_time);
           AMREX_ALWAYS_ASSERT(flag == 0);
         }
 
         // Set max number of steps between returns
-        ARKStepSetMaxNumSteps(arkode_mem, max_num_steps);
+        MRIStepSetMaxNumSteps(arkode_mem, max_num_steps);
```
Comment (WeiqunZhang) [inline Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H]: Missing `flag =` here?

Comment (gardner48) [reply Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H]: The missing `flag =` is addressed in #5092 but I can pull those changes into this PR if that's easier

Comment (WeiqunZhang) [reply Src/Extern/SUNDIALS/AMReX_SundialsIntegrator.H]: I see. I can merge that PR first. But you will need to resolve a conflict.

**Review by WeiqunZhang — APPROVED** [review]
