### PR TITLE
Fix caching mechanism for neighbor particle mask

### LINKED ISSUE #5057: GPU neighbor-mask rebuild path never stabilizes cache and over-synchronizes
- **Type**: Performance / Scalability
- **Severity**: Medium
- **Component**: GPU neighbor fill (`NeighborParticleContainer`)
- **Location**:
  - `Src/Particle/AMReX_NeighborParticlesGPUImpl.H:66`
  - `Src/Particle/AMReX_NeighborParticlesGPUImpl.H:114`

## Problem
`buildNeighborMask()` gates rebuild on `m_neighbor_mask_ptr == nullptr || ...`, but `m_neighbor_mask_ptr` is never assigned anywhere in this GPU path.

That means the expensive rebuild branch is always taken. It also calls `Gpu::streamSynchronize()` inside the per-grid loop, forcing repeated host/device synchronization.

## Impact
- Rebuild work repeats even when BA/DM are unchanged.
- Per-grid synchronization serializes GPU-side setup and hurts strong scaling.

## Suggested patch
Use explicit cached BA/DM refs for invalidation and synchronize once after the loop.

```diff
--- a/Src/Particle/AMReX_NeighborParticlesGPUImpl.H
+++ b/Src/Particle/AMReX_NeighborParticlesGPUImpl.H
@@
-    if (m_neighbor_mask_ptr == nullptr ||
-        ! BoxArray::SameRefs(m_neighbor_mask_ptr->boxArray(), ba) ||
-        ! DistributionMapping::SameRefs(m_neighbor_mask_ptr->DistributionMap(), dmap))
+    if (!m_neighbor_mask_initialized ||
+        !BoxArray::SameRefs(m_cached_neighbor_ba, ba) ||
+        !DistributionMapping::SameRefs(m_cached_neighbor_dm, dmap))
     {
+        neighbor_procs.clear();
@@
-            Gpu::streamSynchronize();
         }
+
+        Gpu::streamSynchronize();
+        m_cached_neighbor_ba = ba;
+        m_cached_neighbor_dm = dmap;
+        m_neighbor_mask_initialized = true;

         RemoveDuplicates(neighbor_procs);
     }
```

(Requires adding `m_cached_neighbor_ba` and `m_cached_neighbor_dm` members.)

Prepared by Codex

### PR DESCRIPTION
**Pull request by atmyers**
Closes #5057.

The proposed changes:
- [x] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

File: Src/Particle/AMReX_NeighborParticlesGPUImpl.H [hunk 1]
```diff
@@ -110,10 +110,12 @@ buildNeighborMask ()
             m_isec_boxes[grid].resize(h_isec_boxes.size());
             Gpu::copyAsync(Gpu::hostToDevice, h_isec_boxes.begin(), h_isec_boxes.end(),
                       m_isec_boxes[grid].begin());
-
-            Gpu::streamSynchronize();
         }
 
+        Gpu::streamSynchronize();
```
Comment (WeiqunZhang) [inline Src/Particle/AMReX_NeighborParticlesGPUImpl.H]: This is not needed because MFIter does sync already.

File: Src/Particle/AMReX_NeighborParticlesGPUImpl.H [hunk 2]
```diff
@@ -110,10 +110,12 @@ buildNeighborMask ()
             m_isec_boxes[grid].resize(h_isec_boxes.size());
             Gpu::copyAsync(Gpu::hostToDevice, h_isec_boxes.begin(), h_isec_boxes.end(),
                       m_isec_boxes[grid].begin());
-
-            Gpu::streamSynchronize();
```
Comment (WeiqunZhang) [inline Src/Particle/AMReX_NeighborParticlesGPUImpl.H:114]: I don't think we can remove this streamSynchronize. It's here to protect against the destruction of the two host vectors defined inside the MFIter loop.

**Review by WeiqunZhang — APPROVED** [review]
