### PR TITLE
Fix warning in FabSet for single precision

### LINKED ISSUE #1479: FabSet Warning in SP
Seen with Intel `icpc` from oneAPI beta09 (single-precision compile) and `-Werror`:
```
Src/Boundary/AMReX_FabSet.cpp(184): error #264: floating-point value does not fit in required floating-point type
          AMREX_HOST_DEVICE_PARALLEL_FOR_4D ( bx, ncomp, i, j, k, n,
          ^

Src/Boundary/AMReX_FabSet.cpp(184): error #264: floating-point value does not fit in required floating-point type
          AMREX_HOST_DEVICE_PARALLEL_FOR_4D ( bx, ncomp, i, j, k, n,
          ^
```

### PR DESCRIPTION
**Pull request by WeiqunZhang**
## Checklist

The proposed changes:
- [x] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate

### CODE REVIEW

File: Src/Boundary/AMReX_FabSet.cpp [hunk 1]
```diff
@@ -181,10 +181,15 @@ FabSet::linComb (Real a, const MultiFab& mfa, int a_comp,
         const Box& bx = mfi.validbox();
         auto afab = bdrya.array(mfi);
         auto bfab = bdryb.array(mfi);
+#ifdef AMREX_USE_FLOAT
+        Real huge = 1.e30f;
+#else
+        Real huge = 1.e200;
```
Comment (ax3l) [inline Src/Boundary/AMReX_FabSet.cpp]:
```suggestion
        const Real huge = 1.e30f;
#else
        const Real huge = 1.e200;
```

**Review by ax3l — APPROVED** [review]
Thank you! :sparkles:
