### PR TITLE
Fix race condition with TinyProfiler for memory

### LINKED ISSUE #3156: The_Pinned_Arena uses a CArena on CPU
If `AMREX_USE_GPU=FALSE`, then The_Arena, The_Device_Arena and The_Managed_Arena are all BArenas rather than CArenas like on GPU. However, The_Pinned_Arena stays a CArena but returns false when Arena::isPinned() is called. This causes it to share TinyProfiler memory diagnostics with amrex_mempool:
```
Cpu (amrex_mempool) Memory Usage:
---------------------------------------------------------------------------------------------------------------------
Name                            Nalloc  Nfree  AvgMem min  AvgMem avg  AvgMem max  MaxMem min  MaxMem avg  MaxMem max
---------------------------------------------------------------------------------------------------------------------
Hipace::Notify()                   150    150      10 MiB      10 MiB      11 MiB      12 MiB      12 MiB      12 MiB
Hipace::Wait()                     150    150     424 KiB     424 KiB     425 KiB      12 MiB      12 MiB      12 MiB
The_Pinned_Arena::Initialize()       2      2      11   B      12   B      14   B    8192 KiB    8192 KiB    8192 KiB
amrex_mempool_init()                 4      4    7219   B    7222   B    7225   B    8192 KiB    8192 KiB    8192 KiB
Hipace::Evolve()                     2      2     452 KiB     475 KiB     497 KiB     500 KiB     500 KiB     500 KiB
main()                              62     62      15   B      15   B      15   B      48   B      48   B      48   B
---------------------------------------------------------------------------------------------------------------------
```
This is an issue because the underlying map used for profiling relies on the mutex of the CArena to be thread save, but now there are two mutexes for the same map.
The following setup should maybe cause a race condition with AMREX_USE_GPU=FALSE.
```
#pragma omp parallel
{
    BL_PROFILE("Test");
    if (omp_get_thread_num() == 0) {
        // allocate from The_Pinned_Arena
    } else {
        // allocate from amrex_mempool
    } 
}
```

### PR DESCRIPTION
**Pull request by AlexanderSinn**
## Summary

Fix #3156 by giving every Arena its own map for profiling.  

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

File: Src/Base/AMReX_CArena.H [hunk 1]
```diff
@@ -165,6 +172,11 @@ protected:
     std::size_t m_used;
     //! The amount of memory given out via alloc().
     std::size_t m_actually_used;
+    //! If this arena is profiled by TinyProfiler
+    bool m_do_profiling;
```
Comment (WeiqunZhang) [inline Src/Base/AMReX_CArena.H]: Can we give this a default value?

File: Src/Base/AMReX_TinyProfiler.cpp [hunk 2]
```diff
@@ -347,21 +348,21 @@ TinyProfiler::memory_stop () const noexcept {
 }
 
 MemStat*
-TinyProfiler::memory_alloc (std::size_t nbytes, int memtype) noexcept {
-    // this function is not thread save for the same memtype
+TinyProfiler::memory_alloc (std::size_t nbytes, std::map<std::string, MemStat>& memstats) noexcept {
+    // this function is not thread save for the same memstats
```
Comment (WeiqunZhang) [inline Src/Base/AMReX_TinyProfiler.cpp]:
```suggestion
    // this function is not thread safe for the same memstats
```

File: Src/Base/AMReX_TinyProfiler.cpp [hunk 3]
```diff
@@ -374,7 +375,7 @@ TinyProfiler::memory_alloc (std::size_t nbytes, int memtype) noexcept {
 
 void
 TinyProfiler::memory_free (std::size_t nbytes, MemStat* stat) noexcept {
-    // this function is not thread save for the same memtype
+    // this function is not thread save for the same stat
```
Comment (WeiqunZhang) [inline Src/Base/AMReX_TinyProfiler.cpp]:
```suggestion
    // this function is not thread safe for the same stat
```

**Comment by WeiqunZhang** [comment]
> Now it is important that every profiled Arena is still in scope when the profile is printed.

Maybe the dtor of Arena should deregister itself.

**Comment by WeiqunZhang** [comment]
Could we move the call to `BL_TINY_PROFILE_MEMORYFINALIZE` to right above the call to `amrex_mempool_finalize`?  Currently there is a block of code finalizing `TheFinalize_Function_Stack`, which may contains users' functions deallocating Arena memory.

**Comment by AlexanderSinn** [comment]
I did move `BL_TINY_PROFILE_MEMORYFINALIZE`, however I think that I mixed up the implementation and `Additionally, no profiled memory can be deallocated between finalizing TinyProfiler and finalizing the Arenas now.` is not true. It should work just not show up in the profile of Nfree.
`Now it is important that every profiled Arena is still in scope when the profile is printed. ` is still somewhat true if profiled output is desired, but DeregisterArena would prevent it from crashing now.

File: Src/Base/AMReX_TinyProfiler.cpp [hunk 4]
```diff
@@ -488,9 +491,33 @@ TinyProfiler::MemoryFinalize (bool bFlushing) noexcept
...
+
+void
+TinyProfiler::DeregisterArena (std::map<std::string, MemStat>& memstats) noexcept
+{
+    for (std::size_t i = 0; i < all_memstats.size(); ++i) {
+        if (all_memstats[i] == &memstats) {
+            all_memstats.erase(all_memstats.begin() + i);
+            all_memnames.erase(all_memnames.begin() + i);
+        }
+    }
```
Comment (WeiqunZhang) [inline Src/Base/AMReX_TinyProfiler.cpp]: In practice, this is OK because there is only one element in the vector that can meet the condition (unless one mistakenly calls RegisterArena twice).  If that's the case, we could used `std::find` and then `std::distance` to figure the element index first and then remove them from `all_memestats` and `all_memnames`.  We could also add an AMREX_ASSERT() in the end to make sure there are no more matches.  I think the code will be more readable.  The issue of the current code I cannot help noticing it will not work if there two matches in a row because of `++i` and `erase`.

Comment (AlexanderSinn) [reply Src/Base/AMReX_TinyProfiler.cpp]: Good catch, thanks! This is intended to always work.

**Review by WeiqunZhang — APPROVED** [review]
