### PR TITLE
Force the alignment of SoA and AoS Particles 

### LINKED ISSUE #4371: Compiling for 32bit Linux
Compiling AMReX 25.02 for 32bit Linux raises this static assert:
```
src/Particle/ParticleContainer.cpp:52:8:   required from here
2025-03-12T17:03:32.0388802Z   /usr/local/include/AMReX_ParticleContainerI.H:65:61: error: static assertion failed: sizeof ParticleType is not a multiple of sizeof RealType
2025-03-12T17:03:32.0390003Z      65 |         static_assert(sizeof(ParticleType)%sizeof(RealType) == 0,
2025-03-12T17:03:32.0390575Z         |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```
https://github.com/AMReX-Codes/amrex/blob/25.02/Src/Particle/AMReX_ParticleContainerI.H#L65-L66

Seen in
- https://github.com/BLAST-ImpactX/impactx-wheels
- https://github.com/AMReX-Codes/pyamrex/issues/424

### PR DESCRIPTION
**Pull request by WeiqunZhang**
This fixes build issues on 32-bit Linux. This should not affect 64 bits machines.

Fix #4371

### CODE REVIEW

File: Src/Particle/AMReX_ParticleTile.H [hunk 1]
```diff
@@ -311,7 +311,7 @@ struct ParticleTileData
 
 // SOA Particle Structure
 template <int T_NArrayReal, int T_NArrayInt>
-struct ConstSoAParticle : SoAParticleBase
+struct alignas(8) ConstSoAParticle : SoAParticleBase
```
Comment (WeiqunZhang) [inline Src/Particle/AMReX_ParticleTile.H]:
```suggestion
struct alignas(sizeof(double)) ConstSoAParticle : SoAParticleBase
```

File: Src/Particle/AMReX_ParticleTile.H [hunk 2]
```diff
@@ -373,7 +373,7 @@ struct ConstSoAParticle : SoAParticleBase
 };
 
 template <int T_NArrayReal, int T_NArrayInt>
-struct SoAParticle : SoAParticleBase
+struct alignas(8) SoAParticle : SoAParticleBase
```
Comment (WeiqunZhang) [inline Src/Particle/AMReX_ParticleTile.H]:
```suggestion
struct alignas(sizeof(double)) SoAParticle : SoAParticleBase
```

**Comment by ax3l** [comment]
@WeiqunZhang I see still the same error with this patch in https://github.com/BLAST-ImpactX/impactx-wheels/pull/3

**Comment by ax3l** [comment]
Oh, I think I tested the first version. Will restart with the latest changes now.

**Comment by ax3l** [comment]
Ok, improvement. Now only the legacy data type (AoS + SoA) has the same alignment issue, too, e.g., for `amrex::Particle<2, 1>` in `void amrex::ParticleContainer_impl`
```
    [ 60%] Building CXX object _deps/fetchedpyamrex-build/CMakeFiles/pyAMReX_3d.dir/src/Particle/ParticleContainer_FHDeX.cpp.o
    cd /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-build && /opt/rh/devtoolset-10/root/usr/bin/c++ -DAMREX_SPACEDIM=3 -DpyAMReX_3d_EXPORTS -I/project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src -I/usr/local/share/amrex/C_scripts -isystem /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include -isystem /opt/python/cp39-cp39/include/python3.9 -Wall -Wextra -Wpedantic -Wshadow -Woverloaded-virtual -Wunreachable-code -O3 -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -pthread -flto -fno-fat-lto-objects -MD -MT _deps/fetchedpyamrex-build/CMakeFiles/pyAMReX_3d.dir/src/Particle/ParticleContainer_FHDeX.cpp.o -MF CMakeFiles/pyAMReX_3d.dir/src/Particle/ParticleContainer_FHDeX.cpp.o.d -o CMakeFiles/pyAMReX_3d.dir/src/Particle/ParticleContainer_FHDeX.cpp.o -c /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer_FHDeX.cpp
    In file included from /usr/local/include/AMReX_ParticleContainer.H:1542,
                     from /usr/local/include/AMReX_Particles.H:5,
                     from /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.H:20,
                     from /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.cpp:6:
    /usr/local/include/AMReX_ParticleContainerI.H: In instantiation of ‘void amrex::ParticleContainer_impl<ParticleType, NArrayReal, NArrayInt, Allocator, CellAssignor>::Initialize() [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; Allocator = amrex::PinnedArenaAllocator; T_CellAssignor = amrex::DefaultAssignor]’:
    /usr/local/include/AMReX_ParticleContainer.H:204:9:   required from ‘amrex::ParticleContainer_impl<ParticleType, NArrayReal, NArrayInt, Allocator, CellAssignor>::ParticleContainer_impl() [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; Allocator = amrex::PinnedArenaAllocator; T_CellAssignor = amrex::DefaultAssignor]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include/pybind11/detail/init.h:76:12:   required from ‘Class* pybind11::detail::initimpl::construct_or_initialize(Args&& ...) [with Class = amrex::ParticleContainer_impl<amrex::Particle<2, 1>, 3, 1, amrex::PinnedArenaAllocator, amrex::DefaultAssignor>; Args = {}; typename std::enable_if<std::is_constructible<_Tp, _Args>::value, int>::type <anonymous> = 0]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include/pybind11/detail/init.h:208:70:   required from ‘static void pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<amrex::ParticleContainer_impl<amrex::Particle<2, 1>, 3, 1, amrex::PinnedArenaAllocator, amrex::DefaultAssignor> >; Extra = {}; typename std::enable_if<(! Class::has_alias), int>::type <anonymous> = 0; Args = {}]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include/pybind11/pybind11.h:1659:21:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const pybind11::detail::initimpl::constructor<Args ...>&, const Extra& ...) [with Args = {}; Extra = {}; type_ = amrex::ParticleContainer_impl<amrex::Particle<2, 1>, 3, 1, amrex::PinnedArenaAllocator, amrex::DefaultAssignor>; options = {}]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.H:178:13:   required from ‘void make_ParticleContainer_and_Iterators(pybind11::module&, std::string) [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; Allocator = amrex::PinnedArenaAllocator; pybind11::module = pybind11::module_; std::string = std::basic_string<char>]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.H:513:41:   required from ‘void make_ParticleContainer_and_Iterators(pybind11::module&) [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; pybind11::module = pybind11::module_]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.cpp:57:65:   required from here
    /usr/local/include/AMReX_ParticleContainerI.H:77:61: error: static assertion failed: sizeof ParticleType is not a multiple of sizeof RealType
       77 |         static_assert(sizeof(ParticleType)%sizeof(RealType) == 0,
          |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
    /usr/local/include/AMReX_ParticleContainerI.H: In instantiation of ‘void amrex::ParticleContainer_impl<ParticleType, NArrayReal, NArrayInt, Allocator, CellAssignor>::Initialize() [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; Allocator = std::allocator; T_CellAssignor = amrex::DefaultAssignor]’:
    /usr/local/include/AMReX_ParticleContainer.H:204:9:   required from ‘amrex::ParticleContainer_impl<ParticleType, NArrayReal, NArrayInt, Allocator, CellAssignor>::ParticleContainer_impl() [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; Allocator = std::allocator; T_CellAssignor = amrex::DefaultAssignor]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include/pybind11/detail/init.h:76:12:   required from ‘Class* pybind11::detail::initimpl::construct_or_initialize(Args&& ...) [with Class = amrex::ParticleContainer_impl<amrex::Particle<2, 1>, 3, 1, std::allocator, amrex::DefaultAssignor>; Args = {}; typename std::enable_if<std::is_constructible<_Tp, _Args>::value, int>::type <anonymous> = 0]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include/pybind11/detail/init.h:208:70:   required from ‘static void pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<amrex::ParticleContainer_impl<amrex::Particle<2, 1>, 3, 1, std::allocator, amrex::DefaultAssignor> >; Extra = {}; typename std::enable_if<(! Class::has_alias), int>::type <anonymous> = 0; Args = {}]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include/pybind11/pybind11.h:1659:21:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const pybind11::detail::initimpl::constructor<Args ...>&, const Extra& ...) [with Args = {}; Extra = {}; type_ = amrex::ParticleContainer_impl<amrex::Particle<2, 1>, 3, 1, std::allocator, amrex::DefaultAssignor>; options = {}]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.H:178:13:   required from ‘void make_ParticleContainer_and_Iterators(pybind11::module&, std::string) [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; Allocator = std::allocator; pybind11::module = pybind11::module_; std::string = std::basic_string<char>]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.H:531:37:   required from ‘void make_ParticleContainer_and_Iterators(pybind11::module&) [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; pybind11::module = pybind11::module_]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.cpp:57:65:   required from here
    /usr/local/include/AMReX_ParticleContainerI.H:77:61: error: static assertion failed: sizeof ParticleType is not a multiple of sizeof RealType
    /usr/local/include/AMReX_ParticleContainerI.H: In instantiation of ‘void amrex::ParticleContainer_impl<ParticleType, NArrayReal, NArrayInt, Allocator, CellAssignor>::Initialize() [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; Allocator = amrex::ArenaAllocator; T_CellAssignor = amrex::DefaultAssignor]’:
    /usr/local/include/AMReX_ParticleContainer.H:204:9:   required from ‘amrex::ParticleContainer_impl<ParticleType, NArrayReal, NArrayInt, Allocator, CellAssignor>::ParticleContainer_impl() [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; Allocator = amrex::ArenaAllocator; T_CellAssignor = amrex::DefaultAssignor]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include/pybind11/detail/init.h:76:12:   required from ‘Class* pybind11::detail::initimpl::construct_or_initialize(Args&& ...) [with Class = amrex::ParticleContainer_impl<amrex::Particle<2, 1>, 3, 1, amrex::ArenaAllocator, amrex::DefaultAssignor>; Args = {}; typename std::enable_if<std::is_constructible<_Tp, _Args>::value, int>::type <anonymous> = 0]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include/pybind11/detail/init.h:208:70:   required from ‘static void pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<amrex::ParticleContainer_impl<amrex::Particle<2, 1>, 3, 1, amrex::ArenaAllocator, amrex::DefaultAssignor> >; Extra = {}; typename std::enable_if<(! Class::has_alias), int>::type <anonymous> = 0; Args = {}]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpybind11-src/include/pybind11/pybind11.h:1659:21:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const pybind11::detail::initimpl::constructor<Args ...>&, const Extra& ...) [with Args = {}; Extra = {}; type_ = amrex::ParticleContainer_impl<amrex::Particle<2, 1>, 3, 1, amrex::ArenaAllocator, amrex::DefaultAssignor>; options = {}]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.H:178:13:   required from ‘void make_ParticleContainer_and_Iterators(pybind11::module&, std::string) [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; Allocator = amrex::ArenaAllocator; pybind11::module = pybind11::module_; std::string = std::basic_string<char>]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.H:533:35:   required from ‘void make_ParticleContainer_and_Iterators(pybind11::module&) [with T_ParticleType = amrex::Particle<2, 1>; int T_NArrayReal = 3; int T_NArrayInt = 1; pybind11::module = pybind11::module_]’
    /project/build/temp.linux-i686-cpython-39/Release/_deps/fetchedpyamrex-src/src/Particle/ParticleContainer.cpp:57:65:   required from here
    /usr/local/include/AMReX_ParticleContainerI.H:77:61: error: static assertion failed: sizeof ParticleType is not a multiple of sizeof RealType
```

**Comment by ax3l** [comment]
Oh wait, that was patched here as well. So does not work just yet it seems.

**Comment by ax3l** [comment]
Added a CI runner and fixed a few more musl issues in #4385

Maybe the patch here does work after all :)

**Comment by ax3l** [comment]
Added a CI runner that shows the issue (and fixed a few more musl issues in #4385 on the way).

Status is still:
```
/home/runner/work/amrex/amrex/Src/Particle/AMReX_ParticleContainerI.H:77:61: error: static assertion failed: sizeof ParticleType is not a multiple of sizeof RealType
   77 |         static_assert(sizeof(ParticleType)%sizeof(RealType) == 0,
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/runner/work/amrex/amrex/Src/Particle/AMReX_ParticleContainerI.H:77:61: note: the comparison reduces to '(4 == 0)'
```
If you have more ideas, you can push them here and see if the AlpineLinux runner passes.

**Comment by WeiqunZhang** [comment]
There might be a compiler bug that does not treat multiple alignas statements correctly. It is supposed to use the strictest one, but it might be using the last one. If I only use one, the Particle CI tests pass.

**Review by atmyers — APPROVED** [review]

**Comment by ax3l** [comment]
Yay, works for ImpactX  25.04+ now: https://github.com/BLAST-ImpactX/impactx-wheels/pull/6 :tada:
