### PR TITLE
DataServices: Qualify math functions with `std::` namespace specifier

### LINKED ISSUE #3405: AMRProfParser compile error
When I try to build the AMRProfParser with GCC 11.3.0 (I have also tried GCC 13.1.1 and Clang 16.0.5), I get the following compiler error:
```
../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp: In member function 'void amrex::DataServices::RunTimelinePF(std::map<int, std::__cxx11::basic_string<char> >&, std::string&, BLProf
Stats::TimeRange&, int, int, int, bool&)':
../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:2491:32: error: no matching function for call to 'pow(int, int)'                                                                   
 2491 |             ntnMultiplier = pow(10, static_cast<int>( 1 + log10(ntnSize)));
      |                             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../amrex/Src/Base/AMReX_ParallelDescriptor.H:13,
                 from ../../../amrex/Src/Base/AMReX_DistributionMapping.H:10,
                 from ../../../amrex/Src/Base/AMReX_Utility.H:13,
                 from ../../../amrex/Src/Base/AMReX_BaseFab.H:19,
                 from ../../../amrex/Src/Base/AMReX_FArrayBox.H:6,
                 from ../../../amrex/Src/Base/AMReX_MultiFab.H:7,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_AmrData.H:11,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_DataServices.H:10,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:5:
../../../amrex/Src/Base/AMReX_GpuComplex.H:415:15: note: candidate: 'template<class T> amrex::GpuComplex<T> amrex::pow(const amrex::GpuComplex<T>&, const T&)'
  415 | GpuComplex<T> pow (const GpuComplex<T>& a_z, const T& a_y) noexcept
      |               ^~~
../../../amrex/Src/Base/AMReX_GpuComplex.H:415:15: note:   template argument deduction/substitution failed:
../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:2491:32: note:   mismatched types 'const amrex::GpuComplex<T>' and 'int'
 2491 |             ntnMultiplier = pow(10, static_cast<int>( 1 + log10(ntnSize)));
      |                             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../amrex/Src/Base/AMReX_ParallelDescriptor.H:13,
                 from ../../../amrex/Src/Base/AMReX_DistributionMapping.H:10,
                 from ../../../amrex/Src/Base/AMReX_Utility.H:13,
                 from ../../../amrex/Src/Base/AMReX_BaseFab.H:19,
                 from ../../../amrex/Src/Base/AMReX_FArrayBox.H:6,
                 from ../../../amrex/Src/Base/AMReX_MultiFab.H:7,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_AmrData.H:11,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_DataServices.H:10,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:5:
../../../amrex/Src/Base/AMReX_GpuComplex.H:448:15: note: candidate: 'template<class T> amrex::GpuComplex<T> amrex::pow(const amrex::GpuComplex<T>&, int)'
  448 | GpuComplex<T> pow (const GpuComplex<T>& a_z, int a_n) noexcept
      |               ^~~
../../../amrex/Src/Base/AMReX_GpuComplex.H:448:15: note:   template argument deduction/substitution failed:
../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:2491:32: note:   mismatched types 'const amrex::GpuComplex<T>' and 'int'
 2491 |             ntnMultiplier = pow(10, static_cast<int>( 1 + log10(ntnSize)));
      |                             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:2504:31: error: no matching function for call to 'pow(int, int)'
 2504 |             bnMultiplier = pow(10, static_cast<int>( 1 + log10(bnSize)));
      |                            ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../amrex/Src/Base/AMReX_ParallelDescriptor.H:13,
                 from ../../../amrex/Src/Base/AMReX_DistributionMapping.H:10,
                 from ../../../amrex/Src/Base/AMReX_Utility.H:13,
                 from ../../../amrex/Src/Base/AMReX_BaseFab.H:19,
                 from ../../../amrex/Src/Base/AMReX_FArrayBox.H:6,
                 from ../../../amrex/Src/Base/AMReX_MultiFab.H:7,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_AmrData.H:11,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_DataServices.H:10,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:5:
../../../amrex/Src/Base/AMReX_GpuComplex.H:415:15: note: candidate: 'template<class T> amrex::GpuComplex<T> amrex::pow(const amrex::GpuComplex<T>&, const T&)'
  415 | GpuComplex<T> pow (const GpuComplex<T>& a_z, const T& a_y) noexcept
      |               ^~~
../../../amrex/Src/Base/AMReX_GpuComplex.H:415:15: note:   template argument deduction/substitution failed:
../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:2504:31: note:   mismatched types 'const amrex::GpuComplex<T>' and 'int'
 2504 |             bnMultiplier = pow(10, static_cast<int>( 1 + log10(bnSize)));
      |                            ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../amrex/Src/Base/AMReX_ParallelDescriptor.H:13,
                 from ../../../amrex/Src/Base/AMReX_DistributionMapping.H:10,
                 from ../../../amrex/Src/Base/AMReX_Utility.H:13,
                 from ../../../amrex/Src/Base/AMReX_BaseFab.H:19,
                 from ../../../amrex/Src/Base/AMReX_FArrayBox.H:6,
                 from ../../../amrex/Src/Base/AMReX_MultiFab.H:7,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_AmrData.H:11,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_DataServices.H:10,
                 from ../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:5:
../../../amrex/Src/Base/AMReX_GpuComplex.H:448:15: note: candidate: 'template<class T> amrex::GpuComplex<T> amrex::pow(const amrex::GpuComplex<T>&, int)'
  448 | GpuComplex<T> pow (const GpuComplex<T>& a_z, int a_n) noexcept
      |               ^~~
../../../amrex/Src/Base/AMReX_GpuComplex.H:448:15: note:   template argument deduction/substitution failed:
../../../amrex/Src/Extern/amrdata/AMReX_DataServices.cpp:2504:31: note:   mismatched types 'const amrex::GpuComplex<T>' and 'int'
 2504 |             bnMultiplier = pow(10, static_cast<int>( 1 + log10(bnSize)));
      |                            ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I think it just needs the `std::` namespace qualifier on the `pow()`s.

### PR DESCRIPTION
**Pull request by mirenradia**
## Summary
As in the title. This fixes #3405.

## Additional background
I did briefly look at using `powi`, but I don't think the exponents are known at compile time.

I also added some auto-generated source files to .gitignore.

## Checklist

The proposed changes:
- [x] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] include documentation in the code and/or rst files, if appropriate

### CODE REVIEW

File: Src/Extern/amrdata/AMReX_DataServices.cpp [hunk 1]
```diff
@@ -2488,7 +2488,7 @@ void DataServices::RunTimelinePF(std::map<int, std::string> &mpiFuncNames,
           int ntnSize(nameTagNames.size());
           ntnNumbers.resize(ntnSize, 0.0);
           if(ntnSize > 0) {
-            ntnMultiplier = pow(10, static_cast<int>( 1 + log10(ntnSize)));
+            ntnMultiplier = std::pow(10, static_cast<int>( 1 + log10(ntnSize)));
```
Comment (WeiqunZhang) [inline Src/Extern/amrdata/AMReX_DataServices.cpp]: Let's also update log10 here and the change below.

Comment (mirenradia) [reply Src/Extern/amrdata/AMReX_DataServices.cpp]: Weird that this didn't cause a compile error as for `pow()`.

**Review by WeiqunZhang — APPROVED** [review]
