### PR TITLE
Make sure all ba are defined in test, and only call Init once per PC

### LINKED ISSUE #2243: Test: Particles_GhostsAndVirtuals Problematic
In #2232, I realized that on many compiler combinations the test `Particles_GhostsAndVirtuals` fails with output of the form:
```
MPI initialized with 1 MPI processes
MPI initialized with thread support level 0
AMReX (21.08.0) initialized

Number of particles per cell : 10
Size of domain               : Num levels: 3
128 128 128
Ascii test
Ascii test always uses nx=ny=nz=32, nlevs=3, ProbHi=64
Redistributing from processor 0 to 0
ParticleContainer byte spread across MPI nodes: [1024 (16) ... 1024 (16)] total particles: (16)
ParticleContainer::Redistribute() time: 0.030788753

Total number of particles: 16
ParticleContainer byte spread across MPI nodes: [1024 (16) ... 1024 (16)] total particles: (16)
ParticleContainer::Redistribute() time: 0.002962024

Found sum of virts: 3029.00000028022578
Found sum of virts: 0
Found sum of ghosts: 0
Found sum of ghosts: 3035.00000001795206
Found sum of ghosts: 1005.00000009692667
Original test
RandomPerBox test
0::Assertion `boxes.size() > 0' failed, file "/home/runner/work/amrex/amrex/Src/Base/AMReX_DistributionMapping.cpp", line 1286 !!!
SIGABRT
See Backtrace.0 file for details
```

This might be a dormant bug to investigate.
Once solved, we can enable the test again in CI (currently excluded with `-E Particles_GhostsAndVirtuals` in `ctest`).

### PR DESCRIPTION
**Pull request by jmsexton03**
## Summary

* Fixes a potential indexing issue in rr
* Makes ba[lev] definition use for loop instead of if to allow for nlevs>2
* Don't call ParticleInit functions on non-empty ParticleContainers

## Additional background
This is meant to fix #2243 
The assertions now depend on PR #2248 

## Checklist

The proposed changes:
- [X] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate

### CODE REVIEW

File: Tests/Particles/GhostsAndVirtuals/main.cpp [hunk 1]
```diff
@@ -60,8 +60,9 @@ void test_ghosts_and_virtuals (TestParams& parms)
     Vector<BoxArray> ba(nlevs);
     ba[0].define(domain);
 
+    int n_fine = parms.nx;
     for (int lev = 1; lev < nlevs; lev++) {
-        int n_fine = parms.nx*rr[lev-1];
+        n_fine = rr[lev-1];
```
Comment (ax3l) [inline Tests/Particles/GhostsAndVirtuals/main.cpp]: Comparing with previous value and below (`test_ghosts_and_virtuals_randomperbox`), should this read:
```suggestion
        n_fine *= rr[lev-1];
```
?

Comment (ax3l) [reply Tests/Particles/GhostsAndVirtuals/main.cpp]: It's Friday afternoon, so all I can offer is pattern matching :D

File: Tests/Particles/GhostsAndVirtuals/main.cpp [hunk 2]
```diff
@@ -40,7 +40,7 @@ void test_ghosts_and_virtuals (TestParams& parms)
     const Box domain(domain_lo, domain_hi);
 
     // Define the refinement ratio
-    Vector<int> rr(nlevs-1);
+    Vector<int> rr(nlevs);
     for (int lev = 1; lev < nlevs; lev++)
         rr[lev-1] = 2;
```
Comment (ax3l) [inline Tests/Particles/GhostsAndVirtuals/main.cpp]: Since this is not performance-critical code, you can access with bounds-checked methods here:
```suggestion
        rr.at(lev-1) = 2;
```

File: Tests/Particles/GhostsAndVirtuals/main.cpp [hunk 3]
```diff
@@ -60,8 +60,9 @@ void test_ghosts_and_virtuals (TestParams& parms)
     Vector<BoxArray> ba(nlevs);
     ba[0].define(domain);
 
+    int n_fine = parms.nx;
     for (int lev = 1; lev < nlevs; lev++) {
-        int n_fine = parms.nx*rr[lev-1];
+        n_fine *= rr[lev-1];
```
Comment (ax3l) [inline Tests/Particles/GhostsAndVirtuals/main.cpp]:
```suggestion
        n_fine *= rr.at(lev-1);
```

File: Tests/Particles/GhostsAndVirtuals/main.cpp [hunk 4]
```diff
@@ -349,14 +350,15 @@ void test_ghosts_and_virtuals_randomperbox (TestParams& parms)
     Vector<BoxArray> ba(nlevs);
     ba[0].define(domain);
 
-    if (nlevs > 1) {
-        int n_fine = parms.nx*rr[0];
+    int n_fine = parms.nx;
+    for (int lev = 1; lev < nlevs; lev++) {
+        n_fine *= rr[lev-1];
```
Comment (ax3l) [inline Tests/Particles/GhostsAndVirtuals/main.cpp]:
```suggestion
        n_fine *= rr.at(lev-1);
```

File: Tests/Particles/GhostsAndVirtuals/main.cpp [hunk 5]
```diff
@@ -329,7 +330,7 @@ void test_ghosts_and_virtuals_randomperbox (TestParams& parms)
     const Box domain(domain_lo, domain_hi);
 
     // Define the refinement ratio
-    Vector<int> rr(nlevs-1);
+    Vector<int> rr(nlevs);
     for (int lev = 1; lev < nlevs; lev++)
         rr[lev-1] = 2;
```
Comment (ax3l) [inline Tests/Particles/GhostsAndVirtuals/main.cpp]:
```suggestion
        rr.at(lev-1) = 2;
```

File: Tests/Particles/GhostsAndVirtuals/main.cpp [hunk 6]
```diff
@@ -349,14 +350,15 @@ void test_ghosts_and_virtuals_randomperbox (TestParams& parms)
...
+    int n_fine = parms.nx;
+    for (int lev = 1; lev < nlevs; lev++) {
+        n_fine *= rr[lev-1];
         IntVect refined_lo(AMREX_D_DECL(n_fine/4,n_fine/4,n_fine/4));
         IntVect refined_hi(AMREX_D_DECL(3*n_fine/4-1,3*n_fine/4-1,3*n_fine/4-1));
 
         // Build a box for the level 1 domain
         Box refined_patch(refined_lo, refined_hi);
-        ba[1].define(refined_patch);
+        ba[lev].define(refined_patch);
```
Comment (ax3l) [inline Tests/Particles/GhostsAndVirtuals/main.cpp]:
```suggestion
        ba.a(lev).define(refined_patch);
```

File: Tests/Particles/GhostsAndVirtuals/main.cpp [hunk 7]
```diff
@@ -479,7 +486,7 @@ void test_ghosts_and_virtuals_onepercell (TestParams& parms)
     const Box domain(domain_lo, domain_hi);
 
     // Define the refinement ratio
-    Vector<int> rr(nlevs-1);
+    Vector<int> rr(nlevs);
     for (int lev = 1; lev < nlevs; lev++)
         rr[lev-1] = 2;
```
Comment (ax3l) [inline Tests/Particles/GhostsAndVirtuals/main.cpp]:
```suggestion
        rr.at(lev-1) = 2;
```

**Review by ax3l — COMMENTED** [review]
LGTM, thank you.
Little comment on `std::vector::at` that can catch this: https://en.cppreference.com/w/cpp/container/vector/at

Will push a PR to your branch to enable CI.

**Comment by WeiqunZhang** [comment]
Vector::operator[] can catch out of bound error when assertion or debug is
on.

**Comment by ax3l** [comment]
That seems to be GNU libstdc++ specific though: https://stackoverflow.com/a/48804020/2719194

Since the code parts are not in hot loops here, I would exercise the `.at()` that would have caught the original UB issue with any C++ implementation.

**Comment by WeiqunZhang** [comment]
Oh I was talking about amrex::Vector.

**Comment by ax3l** [comment]
Oh yes, you overwrite `operator[]` after deriving from `std::vector` - smart.

**Review by WeiqunZhang — APPROVED** [review]
